import"./assets/styles-BTCk1MES.js";import{a as d,i as u}from"./assets/vendor-BLO6kU33.js";const m="https://dummyjson.com/products";async function l(t=1){try{return(await d.get(m,{params:{limit:12,skip:(t-1)*12}})).data}catch(e){return u.error({title:"error",message:`Помилка при завантаженні зображень:, ${e.message}`,timeout:3e3,position:"topRight"}),null}}async function h(t){try{return(await d.get(m+`/${t}`)).data}catch(e){return u.error({title:"error",message:`Помилка при завантаженні зображень:, ${e.message}`,timeout:3e3,position:"topRight"}),null}}async function f(t,e=1){try{return(await d.get(m+"/search",{params:{q:t,limit:12,skip:(e-1)*12}})).data}catch(r){return u.error({title:"error",message:`Помилка при завантаженні зображень:, ${r.message}`,timeout:3e3,position:"topRight"}),null}}async function g(){try{return(await d.get(m+"/category-list")).data}catch(t){return u.error({title:"error",message:`Помилка при завантаженні зображень:, ${t.message}`,timeout:3e3,position:"topRight"}),null}}async function _(t,e=1){try{return(await d.get(m+`/category/${t}`,{params:{limit:12,skip:(e-1)*12}})).data}catch(r){return u.error({title:"error",message:`Помилка при завантаженні зображень:, ${r.message}`,timeout:3e3,position:"topRight"}),null}}function L(t,e){const r=document.querySelector(".load-more-btn");if(!r||!e||typeof e.total!="number")return;const s=t*12,c=e.total,a=s<c;a&&r.classList.contains("is-hidden")?r.classList.remove("is-hidden"):!a&&!r.classList.contains("is-hidden")&&r.classList.add("is-hidden")}function n(t,e=l(t)){const r=document.querySelector(".products");e.then(s=>{s&&s.products&&(s.products.forEach(c=>{const a=document.createElement("li");a.classList.add("products__item"),a.dataset.id=c.id,a.innerHTML=`
    <img class="products__image" src="${c.images[0]}" alt=""/>
    <p class="products__title">${c.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${c.brand}</span></p>
    <p class="products__category">Category:${c.category} </p>
    <p class="products__price">Price:${c.price} $</p>
        `,r.appendChild(a)}),L(t,s))})}function C(t=g()){const e=document.querySelector(".categories");e&&t.then(r=>r.forEach(s=>{const c=document.createElement("li");c.classList.add("categories__item"),c.innerHTML=`<button class="categories__btn" type="button">${s}</button>`,e.appendChild(c)}))}function p(){document.querySelectorAll(".categories__btn--active").forEach(t=>{t.classList.remove("categories__btn--active")})}function b(t){const e=document.querySelector(".modal-product");e&&(e.innerHTML=`
    <div class="modal-product">
      <img class="modal-product__image" src="${t.images[0]}" alt="${t.title}" />
      <h2 class="modal-product__title">${t.title}</h2>
      <p class="modal-product__brand">Brand: ${t.brand}</p>
      <p class="modal-product__category">Category: ${t.category}</p>
      <p class="modal-product__price">Price: ${t.price} $</p>
      <p class="modal-product__description">${t.description}</p>
    </div>
  `)}let o=1;const S=document.querySelector(".load-more-btn"),$=document.querySelector(".categories");let i=null;const q=document.querySelector(".search-form"),v=document.querySelector(".search-form__btn-clear"),y=document.querySelector(".modal");document.querySelector(".modal-product__btn");const E=document.querySelector(".modal-product__actions"),x=document.querySelector(".products"),k=document.querySelector(".modal__close-btn");addEventListener("DOMContentLoaded",()=>{n(o,l(o)),C(g())});S.addEventListener("click",()=>{o++,i===null?n(o,l(o)):n(o,_(i,o))});$.addEventListener("click",t=>{if(p(),t.target.classList.contains("categories__btn")){const e=t.target.textContent;i=e,o=1;const r=document.querySelector(".products");if(r.innerHTML="",t.target.classList.contains("categories__btn--active")){t.target.classList.remove("categories__btn--active"),i=null,n(o,l(o));return}t.target.textContent==="ALL"&&(i=null,n(o,l(o))),t.target.classList.add("categories__btn--active"),n(o,_(e,o=1))}});q.addEventListener("submit",t=>{t.preventDefault();const e=document.querySelector(".products");e.innerHTML="";const r=document.querySelector(".search-form__input").value.trim();n(o,f(r,o)),p(),i=null});v.addEventListener("click",()=>{const t=document.querySelector(".search-form__input");t.value="";const e=document.querySelector(".products");e.innerHTML="",n(o,l(o)),p(),i=null});x.addEventListener("click",async t=>{const e=t.target.closest(".products__item");if(!e)return;const r=e.dataset.id;try{const s=await h(r);b(s),y.classList.add("modal--is-open")}catch(s){console.error("Ошибка при получении продукта:",s)}});k.addEventListener("click",()=>{y.classList.remove("modal--is-open")});E.addEventListener("click",t=>{t.target.textContent.trim()==="Add to Wishlist"?(t.target.textContent="Remove from Wishlist",t.target.classList.remove("modal-product__btn--wishlist")):t.target.textContent.trim()==="Remove from Wishlist"?(t.target.textContent="Add to Wishlist",t.target.classList.add("modal-product__btn--wishlist")):t.target.textContent.trim()==="Add to Cart"?(t.target.textContent="Remove from Cart",t.target.classList.remove("modal-product__btn--cart")):t.target.textContent.trim()==="Remove from Cart"&&(t.target.textContent="Add to Cart",t.target.classList.add("modal-product__btn--cart"))});
//# sourceMappingURL=index.js.map
